<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/23
 * Time: 11:01
 */
namespace app\index\controller;

use think\Controller;
use think\Request;
use think\Session;

/**
 * Class Auth  用户登录状态类
 * @package app\index\controller
 */
class Auth extends Controller{


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //$this->request = $request;
        //判断是否登录
        $login = $this->is_login();
//        if($login == -1 ){
//            $this->error('请先登录',url('index/login/login'));
//        }
//        echo Request::instance()->module();
//        echo Request::instance()->controller();
//        echo Request::instance()->action();

    }

    //判断是否登录
    public function is_login(){
        $user = Session::get('user_id');
        if(empty($user)){
            return -1;
        }
        return 1;

    }

    

    public function captcha($id= ''){

            return captcha_img($id);

    }

    public function get_user(){
        return Session::get('user_id');

    }


}